POST http://127.0.0.1:8000/login
Content-Type: application/json

{"email": "hoge@hoge.com", "password": "Password"}

###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username": "hoge2", "email": "hoge2@hoge.com", "password": "Password"}

###
GET http://127.0.0.1:8000/todo-list
Content-Type: application/json
Authorization: Token

###
GET http://127.0.0.1:8000/todo-list/3
Content-Type: application/json
Authorization: Token

###
PUT http://127.0.0.1:8000/todo-list/5
Content-Type: application/json
Authorization: Token

{"title": "new title", "status": 3}
